name: "multi event pipelinge / workflow"

on:
    push:   #event 
        branches:
            - master
            - test
    pull_request:
        branches:
            - master 
        types:
            - closed
            - opened 
    workflow_dispatch:




jobs:
    
    on-push:  #job name
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: #steps to be executed 
            - name: "Running on master branch"
              run : echo "Running on master push"



    on-pull_request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run : echo "Running on pull request"


    on-pull_request_closed:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request closed"
              run : echo "Running on pull request closed"

    

    on-workflow_dispatch:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on workflow dispatch"
              run : echo "Running on worlflow dispatch"

