name: "multi event pipelinge / workflow"

on:
    push:
        branches:
            - master
            - test
    pull_request:
        branches:
            - master 
    workflow_dispatch:




jobs:
    
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master branch"
              run : echo "Running on master push"



    on-pull_request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run : echo "Running on pull request"

    on-workflow_dispatch:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on workflow dispatch"
              run : echo "Running on worlflow dispatch"

